### ISSUE TITLE
A possible bug

### ISSUE THREAD

**Issue by ice1000** [unsw-corg/SVF-EclipsePlugin#2]
in `plugin.xml`, this line:
https://github.com/yuleisui/SVF-EclipsePlugin/blob/0bb8ea7dc6eec1448df40f015fa0cdd292bae542/plugin.xml#L26

`uafmarker.sampleBuilder` should probably be an `id`, while the `id` of `uafmarker.builder.SampleBuilder` is actually `sampleBuilder`, not `uafmarker.sampleBuilder`:
https://github.com/yuleisui/SVF-EclipsePlugin/blob/0bb8ea7dc6eec1448df40f015fa0cdd292bae542/plugin.xml#L6

**Comment by yuleisui** [comment]
Hello,

@kaiyangl 

could you please confirm and fix it?

**Comment by ice1000** [comment]
Surprising... The maintainer has replied me.
Unbelievable

**Comment by kaiyangl** [comment]
No there is no bug, this is correct. As the ID for the builder is "sampleBuilder", and the builder is in the plugin called "uafmarker", line 26 is "uafmarker.sampleBuilder" because the "id" on line 26 refers to the id of the builder in the uafmarker plugin, which is related to that specific nature.

**Comment by ice1000** [comment]
@kaiyangl Thanks for your explanation
